l = [10,20,30,40,'a',True]
print(l[0])
print(l[1])
print(l[2])
print(l[3])
print(l[4])
print(l[5])


l=[10,20,30,40,50,60,70,80,90,100]
for x in l:
    if x%20==0:
        print(x)
        
        
        
l =[10,20,30,40,50,60,70,80,90,100]  
l2 = ['a','b','c','d','e']      

l3 = l +l2
print(l3)

print(l2*3)


ll =[l,l2]
print(len(ll))
print(ll)
print(ll[0])


for x in ll:
    print(x)